Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.csv(...)
 2.   └─utils::read.table(...)
 3.     └─base::file(file, "rt")

Quitting from FigureYa101PCA.Rmd:390-421 [unnamed-chunk-5]
Execution halted
